### ISSUE TITLE
Automatically Recognize Patterns

### ISSUE THREAD

**Issue by otaviobarreto** [alexvin8/metatrader4-harm_pets#1]
Hi nice code!, I wanna to ask you if is there a way to make it automatically recognize patterns ?

**Comment by alexvin8** [comment]
Hi, thanks.
If we are talking about this particular indicator then no. And I didn't want to make it automatic. 
But. There are some automatic indicators. I think ZUP is the best one. It has a lot of patterns. You can find it on forexfactory.

**Comment by otaviobarreto** [comment]
Cool, I have Zup indicator also, it's good, but as it's based on zigzag sometimes patterns extends, that's why I was looking for another algorithm, thanks anyway. I will use zup with the fibo confluence to find the best entry point.

**Comment by alexvin8** [comment]
Well, also you can use your hands to draw patterns. It's not so hard))

**Comment by otaviobarreto** [comment]
Yeah, I will also make some modifications, thank you!

**Comment by otaviobarreto** [comment]
Yeah, I will also make some modifications, thank you!
